### PR TITLE
Add blog post about by.http-runner.

### PR DESCRIPTION
**Pull request by andreas-merkel-by**
This adds a blog post about the by.http-runner framework developed at OBY and the lessons we learned from it.

### CODE REVIEW

**Review by sebastian-neubauer-by — CHANGES_REQUESTED** [review]
For my understanding: neither by.http_runner, nor fast_runner are open source or are planned to be open sourced as of yet, right? While I like these kind of posts, there is this feeling "so, what?" talking about a package which is obviously really helpful for us, but we, for unknown reasons, do not open source it...Maybe we find some way out here. Two options I see: not mentioning any internal package at all, purely doing an educational blog post: if you do batch jobs triggered with http, build a shared package that every team uses...this can look something like that <code snippet of usage>...important to consider are: trap1, trap2, trap3...implementation hints: with oss packages like fastapi it is wasy to be implemented <code snippets>
Option 2: why not open sourcing it??? if not the old one, then the new, fast_runner...and probalby defer this blog post until we released version 0.1...
I prefer second option...

**Comment by andreas-merkel-by** [comment]
> For my understanding: neither by.http_runner, nor fast_runner are open source or are planned to be open sourced as of yet, right? 

Yes, I see your point. While I agree that it does not make sense to open source by.http-runner now that we want to get rid of it, I'm also in favor of doing that with fast-http-runner. I'm not involved in the development of the latter, but I'll suggest open sourcing it to Dennis Weyland.

**Comment by andreas-merkel-by** [comment]
In the meantime, I have received positive feedback from the maintainers of fast-http-runner about open sourcing it.

**Comment by sebastian-neubauer-by** [comment]
Awesome, then I would propose the following: prepare open sourcing fast-http-runner (with a better name) and then transform this blog post into a release announcement of the new fast-http-runner (with a better name). I can help you with the preparations for open sourcing it!

**Comment by andreas-merkel-by** [comment]
> Awesome, then I would propose the following: prepare open sourcing fast-http-runner (with a better name) and then transform this blog post into a release announcement of the new fast-http-runner (with a better name). I can help you with the preparations for open sourcing it!

Sounds great! I'm not involved in the development of fast-http-runner, though. Dennis Weyland is coordinating this, so you could get in contact with him concerning open-sourcing.

**Comment by gabriel-kohen-by** [comment]
@andreas-merkel-by  and @sebastian-neubauer-by  is this PR still valid?

**Comment by sebastian-neubauer-by** [comment]
> @andreas-merkel-by and @sebastian-neubauer-by is this PR still valid?

No, I think we can close it.

**Pull request closed without merging**
